# Generated by Django 4.1.4 on 2022-12-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taz',
            name='image',
            field=models.ImageField(upload_to='main_app/static/images/'),
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
                ('taz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.taz')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
