# Generated by Django 4.1.4 on 2023-01-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_feeding_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('DT', 'Diet'), ('SC', 'Social'), ('PH', 'Physical'), ('OT', 'Other')], default='DT', max_length=2)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
