# Generated by Django 4.1.4 on 2023-01-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='taz',
            name='restrictions',
            field=models.ManyToManyField(to='main_app.restriction'),
        ),
    ]
