# Generated by Django 4.1.4 on 2023-01-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_taz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taz',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='taz',
            name='restrictions',
            field=models.ManyToManyField(blank=True, default='', to='main_app.restriction'),
        ),
    ]
