# Generated by Django 4.1.4 on 2023-01-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_taz_image_alter_taz_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taz',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
